services:
  - type: web
    name: packsense
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PORT
        value: 5000
